### ISSUE TITLE
Issues installing Py5

### ISSUE THREAD

**Issue by sbldn** [py5coding/py5generator#465]
Hello, 

I am trying to use py5 on a Raspberry Pi 3B, after the installation everything looks ok, but I got the following message.

```
Traceback (most recent call last):
  File "/home/pi/py5test.py", line 1, in <module>
    import py5
  File "/home/pi/.local/lib/python3.9/site-packages/py5/__init__.py", line 34, in <module>
    import jpype.imports  # noqa
  File "/home/pi/.local/lib/python3.9/site-packages/jpype/__init__.py", line 18, in <module>
    import _jpype
ImportError: /lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/pi/.local/lib/python3.9/site-packages/_jpype.cpython-39-arm-linux-gnueabihf.so)
```

If anyone have an insight about it let me know.

Thanks :)

**Comment by sbldn** [comment]
Hello @hx2A ,
Thanks for giving me a hand on this.

`pi@raspberrypi:~ $ sudo apt search libstdc++
Sorting... Done
Full Text Search... Done
lib32stdc++-6-dev-amd64-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (amd64)

lib32stdc++-6-dev-mips64el-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (mips64el)

lib32stdc++-6-dev-s390x-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (s390x)

lib32stdc++-8-dev-amd64-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (amd64)

lib32stdc++-8-dev-mips64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (mips64)

lib32stdc++-8-dev-mips64el-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (mips64el)

lib32stdc++-8-dev-mips64r6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (mips64r6)

lib32stdc++-8-dev-mips64r6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (mips64r6el)

lib32stdc++-8-dev-ppc64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (ppc64)

lib32stdc++-8-dev-s390x-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (s390x)

lib32stdc++-8-dev-sparc64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (sparc64)

lib32stdc++-8-dev-x32-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (x32)

lib64stdc++-6-dev-i386-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (i386)

lib64stdc++-6-dev-mips-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (mips)

lib64stdc++-6-dev-mipsel-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (mipsel)

lib64stdc++-8-dev-i386-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (i386)

lib64stdc++-8-dev-mips-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (mips)

lib64stdc++-8-dev-mipsel-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (mipsel)

lib64stdc++-8-dev-mipsr6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (mipsr6)

lib64stdc++-8-dev-mipsr6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (mipsr6el)

lib64stdc++-8-dev-powerpc-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (powerpc)

lib64stdc++-8-dev-x32-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (x32)

lib64stdc++6-i386-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (64bit)

lib64stdc++6-mips-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (64bit)

lib64stdc++6-mipsel-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (64bit)

lib64stdc++6-mipsr6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (64bit)

lib64stdc++6-mipsr6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (64bit)

lib64stdc++6-powerpc-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (64bit)

lib64stdc++6-x32-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (64bit)

libc++-11-dev/oldoldstable 1:11.0.1-2~deb10u1+rpi1 armhf
  LLVM C++ Standard library (development files)

libc++-13-dev/oldoldstable 1:13.0.1-6~deb10u4+rpi1 armhf
  LLVM C++ Standard library (development files)

libc++-7-dev/oldoldstable 1:7.0.1-8+rpi3+deb10u2 armhf
  LLVM C++ Standard library (development files)

libc++-8-dev/oldoldstable 1:8-3+rpi1 armhf
  LLVM C++ Standard library (development files)

libc++-9-dev/oldoldstable 1:9.0.1-6+rpi1~bpo10+1 armhf
  LLVM C++ Standard library (development files)

libc++-dev/oldoldstable 1:7.0-47 armhf
  LLVM C++ Standard library (development files)

libc++1/oldoldstable 1:7.0-47 armhf
  LLVM C++ Standard library

libc++1-11/oldoldstable 1:11.0.1-2~deb10u1+rpi1 armhf
  LLVM C++ Standard library

libc++1-13/oldoldstable 1:13.0.1-6~deb10u4+rpi1 armhf
  LLVM C++ Standard library

libc++1-7/oldoldstable 1:7.0.1-8+rpi3+deb10u2 armhf
  LLVM C++ Standard library

libc++1-8/oldoldstable 1:8-3+rpi1 armhf
  LLVM C++ Standard library

libc++1-9/oldoldstable 1:9.0.1-6+rpi1~bpo10+1 armhf
  LLVM C++ Standard library

libgmp-dev/oldoldstable,now 2:6.1.2+dfsg-4+deb10u1 armhf [installed,automatic]
  Multiprecision arithmetic library developers tools

libn32stdc++-6-dev-mips-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (mips)

libn32stdc++-6-dev-mips64el-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (mips64el)

libn32stdc++-6-dev-mipsel-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (mipsel)

libn32stdc++-8-dev-mips-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (mips)

libn32stdc++-8-dev-mips64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (mips64)

libn32stdc++-8-dev-mips64el-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (mips64el)

libn32stdc++-8-dev-mips64r6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (mips64r6)

libn32stdc++-8-dev-mips64r6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (mips64r6el)

libn32stdc++-8-dev-mipsel-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (mipsel)

libn32stdc++-8-dev-mipsr6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (mipsr6)

libn32stdc++-8-dev-mipsr6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files) (mipsr6el)

libn32stdc++6-mips-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (n32)

libn32stdc++6-mips64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (n32)

libn32stdc++6-mips64el-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (n32)

libn32stdc++6-mips64r6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (n32)

libn32stdc++6-mips64r6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (n32)

libn32stdc++6-mipsel-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (n32)

libn32stdc++6-mipsr6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (n32)

libn32stdc++6-mipsr6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (n32)

libstdc++-4.9-dev/oldoldstable 4.9.4-2+rpi1+b19 armhf
  GNU Standard C++ Library v3 (development files)

libstdc++-4.9-doc/oldoldstable 4.9.4-2+rpi1 all
  GNU Standard C++ Library v3 (documentation files)

libstdc++-4.9-pic/oldoldstable 4.9.4-2+rpi1+b19 armhf
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-5-dev/oldoldstable 5.5.0-8 armhf
  GNU Standard C++ Library v3 (development files)

libstdc++-5-doc/oldoldstable 5.5.0-8 all
  GNU Standard C++ Library v3 (documentation files)

libstdc++-5-pic/oldoldstable 5.5.0-8 armhf
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-dev/oldoldstable 6.5.0-1+rpi1+b1 armhf
  GNU Standard C++ Library v3 (development files)

libstdc++-6-dev-amd64-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-6-dev-arm64-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-6-dev-armel-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-6-dev-armhf-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-6-dev-i386-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-6-dev-mips-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-6-dev-mips64el-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-6-dev-mipsel-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-6-dev-ppc64el-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-6-dev-s390x-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-6-doc/oldoldstable 6.5.0-1+rpi1 all
  GNU Standard C++ Library v3 (documentation files)

libstdc++-6-pic/oldoldstable 6.5.0-1+rpi1+b1 armhf
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-pic-amd64-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-pic-arm64-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-pic-armel-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-pic-armhf-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-pic-i386-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-pic-mips-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-pic-mips64el-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-pic-mipsel-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-pic-ppc64el-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-6-pic-s390x-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-7-dev/oldoldstable,now 7.3.0-19 armhf [installed,automatic]
  GNU Standard C++ Library v3 (development files)

libstdc++-7-doc/oldoldstable 7.3.0-19 all
  GNU Standard C++ Library v3 (documentation files)

libstdc++-7-pic/oldoldstable 7.3.0-19 armhf
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-dev/oldoldstable,now 8.3.0-6+rpi1 armhf [installed,automatic]
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-alpha-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-amd64-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-arm64-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-armel-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-armhf-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-hppa-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-i386-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-m68k-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-mips-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-mips64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-mips64el-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-mips64r6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-mips64r6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-mipsel-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-mipsr6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-mipsr6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-powerpc-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-powerpcspe-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-ppc64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-ppc64el-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-riscv64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-s390x-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-sh4-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-sparc64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-dev-x32-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (development files)

libstdc++-8-doc/oldoldstable 8.3.0-6+rpi1 all
  GNU Standard C++ Library v3 (documentation files)

libstdc++-8-pic/oldoldstable 8.3.0-6+rpi1 armhf
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-alpha-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-amd64-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-arm64-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-armel-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-armhf-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-hppa-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-i386-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-m68k-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-mips-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-mips64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-mips64el-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-mips64r6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-mips64r6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-mipsel-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-mipsr6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-mipsr6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-powerpc-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-powerpcspe-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-ppc64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-ppc64el-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-riscv64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-s390x-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-sh4-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-sparc64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-8-pic-x32-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3 (shared library subset kit)

libstdc++-arm-none-eabi-newlib/oldoldstable 15:7-2018-q2-5+12 all
  GNU Standard C++ Library v3 for ARM Cortex-R/M processors (newlib)

libstdc++6/oldoldstable,now 8.3.0-6+rpi1 armhf [installed]
  GNU Standard C++ Library v3

libstdc++6-4.9-dbg/oldoldstable 4.9.4-2+rpi1+b19 armhf
  GNU Standard C++ Library v3 (debugging files)

libstdc++6-5-dbg/oldoldstable 5.5.0-8 armhf
  GNU Standard C++ Library v3 (debugging files)

libstdc++6-6-dbg/oldoldstable 6.5.0-1+rpi1+b1 armhf
  GNU Standard C++ Library v3 (debugging files)

libstdc++6-7-dbg/oldoldstable,now 7.3.0-19 armhf [installed]
  GNU Standard C++ Library v3 (debugging files)

libstdc++6-8-dbg/oldoldstable 8.3.0-6+rpi1 armhf
  GNU Standard C++ Library v3 (debugging files)

libstdc++6-alpha-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-amd64-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3

libstdc++6-arm64-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3

libstdc++6-armel-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3

libstdc++6-armhf-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3

libstdc++6-hppa-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-i386-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3

libstdc++6-m68k-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-mips-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3

libstdc++6-mips64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-mips64el-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3

libstdc++6-mips64r6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-mips64r6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-mipsel-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3

libstdc++6-mipsr6-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-mipsr6el-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-powerpc-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-powerpcspe-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-ppc64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-ppc64el-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3

libstdc++6-riscv64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-s390x-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3

libstdc++6-sh4-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-sparc64-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libstdc++6-x32-cross/oldoldstable 8.3.0-2cross2 all
  GNU Standard C++ Library v3

libx32stdc++-6-dev-amd64-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (amd64)

libx32stdc++-6-dev-i386-cross/oldoldstable 6.4.0-16cross1 all
  GNU Standard C++ Library v3 (development files) (i386)

libx32stdc++-8-dev-amd64-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (amd64)

libx32stdc++-8-dev-i386-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (i386)

libx32stdc++6-amd64-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (x32)

libx32stdc++6-i386-cross/oldoldstable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (x32)
`
I tried to reinstall libstdc++ but I got the same result, I check the GLIBCXX_X.X.X versions on the RP and I got 

`:~ $ strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH
`

**Comment by villares** [comment]
> I am trying to use py5 on a Raspberry Pi 3B, after the installation everything looks ok, but I got the following message.

Maybe @claudafalbriard or @gilfuser can help us on this one?

**Comment by villares** [comment]
@hx2A or @sbldn can you please rename this issue "Issues installing py5 on Raspberry Pi 3B" ?

**Comment by hx2A** [comment]
@sbldn , sorry for my slow responsiveness.

A Processing install is available for the Raspberry pi:

https://processing.org/download

Can you try installing this and seeing if you can get that to work? If this doesn't work then py5 won't be able to work either.

**Comment by villares** [comment]
Next week I might be able to pick a Raspberry Pi at my community center workplace and, if I do, I'll try to install py5.
I think I was able to make Processing work on an older Raspi a few years ago and I think both  @claudefalbriard and @gilfuser also managed to do it, even with py5!  (but I don't know the versions, etc.)

**Comment by hx2A** [comment]
@sbldn , have you been able to get py5 installed on your Raspberry Pi?
