### ISSUE TITLE
Problem importing py5_tools for thonny-py5mode -- but only on Windows

### ISSUE THREAD

**Issue by tabreturn** [py5coding/py5generator#92]
My thonny-py5mode plug-in works fine on macOS and Linux, but fails on Windows. It seems there's an issue importing py5_tools (on Windows only). Does this error make any sense? Any ideas?

```
16:49:30.932 INFO    thonny: Thonny version: 4.0.0b3
16:49:30.948 INFO    thonny: cwd: C:\Users\USER\Desktop\thonny-4.0.0b3-windows-portable
16:49:30.948 INFO    thonny: original argv: []
16:49:30.948 INFO    thonny: sys.executable: C:\Users\USER\Desktop\thonny-4.0.0b3-windows-portable\pythonw.exe
16:49:30.948 INFO    thonny: sys.argv: ['C:\\Users\\USER\\Desktop\\thonny-4.0.0b3-windows-portable\\thonny.exe']
16:49:30.948 INFO    thonny: sys.path: ['C:\\Users\\USER\\Desktop\\thonny-4.0.0b3-windows-portable\\python310.zip', 'C:\\Users\\USER\\Desktop\\thonny-4.0.0b3-windows-portable\\DLLs', 'C:\\Users\\USER\\Desktop\\thonny-4.0.0b3-windows-portable\\lib', 'C:\\Users\\USER\\Desktop\\thonny-4.0.0b3-windows-portable', 'C:\\Users\\USER\\Desktop\\thonny-4.0.0b3-windows-portable\\lib\\site-packages']
16:49:30.948 INFO    thonny: sys.flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=1, no_site=0, ignore_environment=1, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=1, dev_mode=False, utf8_mode=0, warn_default_encoding=0)
16:49:31.313 ERROR   thonny.workbench: Failed loading plugin 'thonnycontrib.thonny-py5mode'
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\thonny-4.0.0b3-windows-portable\lib\site-packages\thonny\workbench.py", line 394, in _load_plugins_from_path
    m = importlib.import_module(module_name)
  File "C:\Users\USER\Desktop\thonny-4.0.0b3-windows-portable\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\Desktop\thonny-4.0.0b3-windows-portable\user_data\plugins\Python310\site-packages\thonnycontrib\thonny-py5mode\__init__.py", line 7, in <module>
    import py5_tools
  File "C:\Users\USER\Desktop\thonny-4.0.0b3-windows-portable\user_data\plugins\Python310\site-packages\py5_tools\__init__.py", line 23, in <module>
    from .imported import set_imported_mode, get_imported_mode  # noqa
  File "C:\Users\USER\Desktop\thonny-4.0.0b3-windows-portable\user_data\plugins\Python310\site-packages\py5_tools\imported.py", line 27, in <module>
    import stackprinter
  File "C:\Users\USER\Desktop\thonny-4.0.0b3-windows-portable\user_data\plugins\Python310\site-packages\stackprinter\__init__.py", line 8, in <module>
    from stackprinter.tracing import TracePrinter, trace
  File "C:\Users\USER\Desktop\thonny-4.0.0b3-windows-portable\user_data\plugins\Python310\site-packages\stackprinter\tracing.py", line 53, in <module>
    class TracePrinter():
  File "C:\Users\USER\Desktop\thonny-4.0.0b3-windows-portable\user_data\plugins\Python310\site-packages\stackprinter\tracing.py", line 82, in TracePrinter
    print_function=sys.stderr.write,
AttributeError: 'NoneType' object has no attribute 'write'
16:49:31.937 INFO    thonny.running: Starting the backend: ['C:\\Users\\USER\\Desktop\\thonny-4.0.0b3-windows-portable\\python.exe', '-u', '-B', '-m', 'thonny.plugins.cpython_backend.cp_launcher', 'C:\\Users\\USER'] C:\Users\USER
16:49:35.553 INFO    thonny.shell: BaseShellText._on_backend_terminated
16:49:35.553 INFO    thonny.running: Reader got EOF
```

**Comment by tabreturn** [comment]
Looks like something Thonny-specific, maybe ... will have to dig a bit deeper ...

**Comment by tabreturn** [comment]
This is a Thonny issue so I'm closing this.
